### ISSUE TITLE
Plugin throwing exception

### ISSUE THREAD

**Issue by Awery123** [Loze-Put/hunllef-helper#33]
The plugin is throwing an exception

```
2023-01-11 19:52:21 [AWT-EventQueue-0] WARN  n.r.client.plugins.PluginManager - Unable to start plugin HunllefHelperPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:467)
	at net.runelite.client.plugins.PluginManager.lambda$startPlugins$2(PluginManager.java:248)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at java.desktop/javax.sound.sampled.AudioSystem.getLine(Unknown Source)
	at java.desktop/javax.sound.sampled.AudioSystem.getClip(Unknown Source)
	at com.hunllefhelper.AudioPlayer.tryLoadClip(AudioPlayer.java:72)
	at com.hunllefhelper.AudioPlayer.tryLoadAudio(AudioPlayer.java:19)
	at com.hunllefhelper.HunllefHelperPlugin.startUp(HunllefHelperPlugin.java:70)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:445)
	... 14 common frames omitted

**Comment by Awery123** [comment]
Cause of issue found: I didn't have any sound output device connected to the PC.
